### ISSUE TITLE
Ubuntu 18.04: ModuleNotFoundError: No module named 'dateparser'

### ISSUE THREAD

**Issue by schmidchr** [hANSIc99/Pythonic#13]
-> complement install instructions with dependencies
 `pip3 install pythonic PyQt5 python-binance pandas`

**Comment by hANSIc99** [comment]
Missing dependency will be fixed in the next release.
Dependencies are generally listed in the setup.py file.

**Comment by hANSIc99** [comment]
Fixed in version 0.10
