### ISSUE TITLE
Raspberry Image

### ISSUE THREAD

**Issue by mchamosa** [hANSIc99/Pythonic#56]
Hello,

I'm trying to install Pythonic on a Raspberry.

I burn the sourceforge.net image on an sd, it starts up I put user and pass and it doesn't continue.

Please, could you tell me how to do it?

Thank you.

**Comment by hANSIc99** [comment]
I need far more information in order to help you.
What doesn't continue?

**Comment by hANSIc99** [comment]
No feedback
