### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [hANSIc99/Pythonic#8]
hi @hANSIc99 I contribute to open source softwares by designing  logos. I guess this software didn't have a logo. so I designed a logo. What do you think about this logo? I will wait for feedback. Have a nice day!

![pythonic](https://user-images.githubusercontent.com/36298335/55291118-09f0fe80-5401-11e9-81a9-4dad7b985a21.jpg)

**Comment by hANSIc99** [comment]
Great! I will definitely implement it this week!

**Comment by reallinfo** [comment]
Please let me know when you  implement. I'll send you a pr with source files. ( If you are not going to make a change in the logo.)

**Comment by hANSIc99** [comment]
Hi,
I would like to integrate the logo in this way (including the lettering):
![Image of Pythonic](https://github.com/hANSIc99/Pythonic/blob/dev/src/Pythonic/images/screenshot-1.png?raw=true)

And on the GitHub page. Can you provide me the source files by mail [mail](mailto:s.avenwedde@gmail.com) or as a pull request to the
[dev](https://github.com/hANSIc99/Pythonic/tree/dev/src/Pythonic/images) branch?

**Comment by reallinfo** [comment]
Sure, I made the latest changes to the logo and sent you all the versions. Png, svg - horizontal, vertical, logomark. I also updated the readme file. You can use it as you wish. Feel free to write me if you need any logo. Have a nice day!
